-- =====================================================================
-- NUVE — flat pricing migration (002)
--
-- Replaces the 3-tier model (sade/klasik/premium) with a single tier
-- called "standard". All invitations now cost the same flat EUR 39.99
-- regardless of template.
-- =====================================================================

-- 1) Backfill any legacy rows to the new tier
update public.invitations
   set tier = 'standard'
 where tier in ('sade', 'klasik', 'premium');

-- 2) Drop the old inline check constraint (name auto-generated by Postgres
--    when the column was defined inline — discover and drop dynamically).
do $$
declare
  con record;
begin
  for con in
    select conname
      from pg_constraint
     where conrelid = 'public.invitations'::regclass
       and contype  = 'c'
       and pg_get_constraintdef(oid) ilike '%tier%'
  loop
    execute format('alter table public.invitations drop constraint %I', con.conname);
  end loop;
end $$;

-- 3) Switch default and add a fresh narrow constraint
alter table public.invitations
  alter column tier set default 'standard';

alter table public.invitations
  add constraint invitations_tier_check check (tier = 'standard');
